export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM: 'CLEAR_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  FETCH_CART_ITEMS_SUCCESS: 'FETCH_CART_ITEMS_SUCCESS',
  FETCH_CART_ITEMS_FAILURE: 'FETCH_CART_ITEMS_FAILURE'
};

export default CartActionTypes;